tac3d_leaphand:
  index:
    geom: leap_hand_right::fingertip_collision
    serial: AD2-0040R
    port: 9988
  middle:
    geom: leap_hand_right::fingertip_2_collision
    serial: AD2-0037L
    port: 9989
  # ring:
  #   geom: leap_hand_right::fingertip_3_collision
  #   serial: AD2-0039L
  #   port: 9990
  # thumb:
  #   geom: leap_hand_right::thumbt_fingertip_collision
  #   serial: AD2-0038R
  #   port: 9991