server_url: /home/jyp/hardware/tac3d/Tac3D-SDK-v3.3.0/Tac3D-Core/linux-x86_64
tac3d:
  # 0
  index:
    geom: leap_hand_right::fingertip_collision
    frame: finger1_tip_center
    # cam_id: 12
    serial: DL1-GWM0005
    port: 9988
  # 1
  middle:
    geom: leap_hand_right::fingertip_2_collision
    frame: finger2_tip_center
    # cam_id: 6
    serial: DL1-GWM0006
    port: 9989
  # 2
  ring:
    geom: leap_hand_right::fingertip_3_collision
    frame: finger3_tip_center
    serial: DL1-GWM0007
    # cam_id: 10
    port: 9990
  # 3
  thumb:
    geom: leap_hand_right::thumb_fingertip_collision
    frame: thumb_tip_center
    serial: DL1-GWM0004
    # cam_id: 8
    port: 9991